### ISSUE TITLE
Stopped updating?

### ISSUE THREAD

**Issue by diplodata** [rs-delve/covid19_datasets#19]
Last update Saturday 0005, meaning Sunday/Monday updates haven't happened. Are you guys on this?

**Comment by avishkar58** [comment]
Hi @diplodata thanks for raising this issue. It stems from the world bank data bank API's SSL certificate failing verification. We are looking into where exactly the problem lies.

**Comment by avishkar58** [comment]
Hi, the issue has been resolved and the dataset has been updated.
