### ISSUE TITLE
No new updates

### ISSUE THREAD

**Issue by DrPav** [rs-delve/covid19_datasets#23]
Hi, the dataset has not been updated since the 27th august. Has it been discontinued?

If the build failed it may be due to the oxford-blavatnik stringency index changed the data format on the 27th August

**Comment by avishkar58** [comment]
Hi @DrPav 
Thank you for raising the issue. The human mortality database has been down the last few days (https://www.mortality.org/) which is causing our build to fail. Since it hasn't been fixed by now I'll add some logic to skip it temporarily.

**Comment by DrPav** [comment]
Thanks @avishkar58

**Comment by avishkar58** [comment]
Dataset has been regenerated without the HMD data
