### ISSUE TITLE
Scotland data source changed format

### ISSUE THREAD

**Issue by ywteh** [rs-delve/covid19_datasets#27]
Hi, it looks like the cases data source from Scotland isn't working now --- https://github.com/DataScienceScotland/COVID-19-Management-Information have changed their data access method 3 days ago.

**Comment by upaq** [comment]
I updated it in commit [f64ca01](https://github.com/rs-delve/covid19_datasets/commit/f64ca01a58b353eb7ac2ee37ad0db0dbd976a365). Coding in production via Github's web interface ;-) as my personal computer lies in Cambridge 6,000 miles away!
